### ISSUE TITLE
Latest version not working with pfUI

### ISSUE THREAD

**Issue by veechs** [luskanek/Flyout#1]
I haven't narrowed down the exact commit, but something broke at some point after May 4. When updated to the latest version, the Flyout arrow no longer appears in pfUI action bars, and clicking the button doesn't summon the menu. Rolling back to the May 4 version got it working again.

Thanks!

**Comment by luskanek** [comment]
Thank you for reporting this. I forgot to edit some important lines while refactoring the code.

Fixed with 3b851b7
